const products=[
{id:1,name:"Samsung Galaxy 5G Smartphone",cat:"Mobiles",price:18999,old:24999,rating:"4.4",img:"https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=700&q=80"},
{id:2,name:"Wireless Noise Cancelling Headphones",cat:"Electronics",price:1499,old:3999,rating:"4.2",img:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=700&q=80"},
{id:3,name:"Running Shoes for Men",cat:"Fashion",price:999,old:2499,rating:"4.3",img:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80"},
{id:4,name:"Smart LED TV 43 inch",cat:"Electronics",price:23999,old:32999,rating:"4.5",img:"https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=700&q=80"},
{id:5,name:"Premium Cotton Bedsheet Set",cat:"Home",price:699,old:1299,rating:"4.1",img:"https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=700&q=80"},
{id:6,name:"Digital Air Fryer",cat:"Appliances",price:2999,old:5999,rating:"4.4",img:"https://images.unsplash.com/photo-1648146299205-2f3f4e9c1b4b?auto=format&fit=crop&w=700&q=80"},
{id:7,name:"Classic Stainless Steel Watch",cat:"Fashion",price:1299,old:2999,rating:"4.0",img:"https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=700&q=80"},
{id:8,name:"Portable Bluetooth Speaker",cat:"Electronics",price:899,old:1999,rating:"4.3",img:"https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=700&q=80"},
{id:9,name:"Gaming Laptop",cat:"Electronics",price:54999,old:69999,rating:"4.6",img:"https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=700&q=80"},
{id:10,name:"Men's Casual Shirt",cat:"Fashion",price:599,old:1199,rating:"4.1",img:"https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=700&q=80"},
{id:11,name:"Beauty Care Essentials",cat:"Beauty",price:799,old:1599,rating:"4.4",img:"https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=700&q=80"},
{id:12,name:"Travel Backpack",cat:"Travel",price:899,old:1799,rating:"4.3",img:"https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=700&q=80"}];
let active="All",cart=[],slide=0;
const $=x=>document.getElementById(x),money=n=>"₹"+n.toLocaleString("en-IN"),off=p=>Math.round((1-p.price/p.old)*100);
function card(p){return `<article class="product" onclick="openProduct(${p.id})"><button class="wish" onclick="event.stopPropagation()">♡</button><div class="pic"><img src="${p.img}" alt="${p.name}" loading="lazy"></div><h3>${p.name}</h3><span class="rating">${p.rating} ★</span><div class="price">${money(p.price)} <del>${money(p.old)}</del> <em>${off(p)}% off</em></div><small>Free delivery</small></article>`}
function render(){let q=$("search").value.toLowerCase().trim(),list=products.filter(p=>(active==="All"||p.cat===active)&&(!q||p.name.toLowerCase().includes(q)||p.cat.toLowerCase().includes(q)));$("grid").innerHTML=list.map(card).join("");$("deals").innerHTML=products.slice(0,6).map(card).join("");$("empty").style.display=list.length?"none":"block";$("result").textContent=list.length+" products";}
function setCat(c){active=c;document.querySelectorAll(".cats button").forEach(b=>b.classList.toggle("active",b.dataset.cat===c));render();document.querySelector("#products").scrollIntoView({behavior:"smooth"});}
document.querySelectorAll(".cats button").forEach(b=>b.onclick=()=>setCat(b.dataset.cat));$("search").oninput=render;
function openProduct(id){let p=products.find(x=>x.id===id);$("detail").innerHTML=`<div class="detail-img"><img src="${p.img}"></div><div class="detail-info"><span class="rating">${p.rating} ★</span><h2>${p.name}</h2><div class="bigprice">${money(p.price)} <del>${money(p.old)}</del></div><p>${off(p)}% off · Free delivery available</p><hr><h4>Product highlights</h4><p>Premium quality product with secure packaging and easy returns.</p><button class="primary" onclick="add(${p.id});closeProduct()">ADD TO CART</button><button class="buy" onclick="add(${p.id});closeProduct();openCart()">BUY NOW</button></div>`;$("productModal").classList.add("show");}
function add(id){let x=cart.find(a=>a.id===id);x?x.qty++:cart.push({id,qty:1});renderCart();}
function renderCart(){$("count").textContent=cart.reduce((a,x)=>a+x.qty,0);$("cartItems").innerHTML=cart.length?cart.map(x=>{let p=products.find(a=>a.id===x.id);return `<div class="cart-item"><img src="${p.img}"><div><b>${p.name}</b><strong>${money(p.price)}</strong><div><button onclick="qty(${p.id},-1)">−</button> ${x.qty} <button onclick="qty(${p.id},1)">+</button></div></div></div>`}).join(""):`<div class="empty-cart">Your cart is empty</div>`;$("total").textContent=money(cart.reduce((a,x)=>a+products.find(p=>p.id===x.id).price*x.qty,0));}
function qty(id,d){let x=cart.find(a=>a.id===id);x.qty+=d;if(x.qty<1)cart=cart.filter(a=>a.id!==id);renderCart();}
function openCart(){$("drawer").classList.add("open");$("overlay").classList.add("show");renderCart()}function closeCart(){$("drawer").classList.remove("open");$("overlay").classList.remove("show")}function closeAll(){closeCart();closeLogin();closeProduct();}
function openLogin(){$("login").classList.add("show")}function closeLogin(){$("login").classList.remove("show")}function closeProduct(){$("productModal").classList.remove("show")}
function login(){if(/^\d{10}$/.test($("phone").value.trim())){alert("Demo login successful");closeLogin()}else alert("Enter a valid 10-digit mobile number")}
function checkout(){if(!cart.length)return alert("Your cart is empty");alert("Checkout UI ready; connect your backend/payment gateway for live orders.")}
function searchProducts(){render();}
let timer=setInterval(()=>next(),6000);
function next(){slide=(slide+1)%3;hero()}function prev(){slide=(slide+2)%3;hero()}function hero(){$(".hero").dataset.slide=slide;$("dots").innerHTML=[0,1,2].map(i=>`<i class="${i===slide?"on":""}"></i>`).join("")}
render();renderCart();hero();